Repository tree-sitter/tree-sitter, pull requests merged in 2023-04, with the labels that each got.

#1884 Fix/subtree and query integer sizing
  lib/src/query.c
  lib/src/subtree.c
Labels: c-library

#1947 Explain naming convention for bindings and parsers
  docs/index.md
Labels: documentation

#2187 CICD: Additional improvements
  .github/workflows/CICD.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/sanitize.yml
Labels: CICD

#2183 fix: Use / paths when building WASM
  Cargo.lock
  cli/Cargo.toml
  cli/src/wasm.rs
Labels: planned-to-merge

#2206 docs: remove controversial statement
  docs/section-3-creating-parsers.md
Labels: documentation
