Repository tree-sitter/tree-sitter, pull requests merged in 2024-10, with the labels that each got.

#2614 feat: allow setting the output directory for the generated C code
  cli/generate/src/lib.rs
  cli/src/main.rs
Labels: cli

#3767 build(deps): bump wasmtime to v25.0.2
  Cargo.lock
  lib/Cargo.toml
Labels: wasm, ci:backport release-0.24

#3779 fix(wasm): fix memory errors in wasm_store
  lib/src/wasm_store.c
Labels: ci:backport release-0.24

#3783 revert: "Memory errors in wasm_store"
  lib/src/wasm_store.c
Labels: ci:backport release-0.24
