Repository tree-sitter/tree-sitter, pull requests merged in 2025-06, with the labels that each got.

#4404 Fix test_flatten_grammar_with_recursive_inline_variable
  cli/generate/src/prepare_grammar/flatten_grammar.rs
Labels: test, ci:backport release-0.25

#4505 fix(loader): fix no-default-features build
  crates/loader/src/loader.rs
Labels: ci:backport release-0.25

#4521 fix(generate): only display conflicting symbol name in non-terminal word token error message if available
  crates/generate/src/prepare_grammar/extract_tokens.rs
Labels: ci:backport release-0.25

#4492 fix(cli): require correct setuptools version
  crates/cli/src/templates/pyproject.toml
Labels: ci:backport release-0.25, build
