Repository tree-sitter/tree-sitter, pull requests merged in 2025-07, with the labels that each got.

#4568 perf: More efficient computation of used symbols
  crates/generate/src/prepare_grammar/flatten_grammar.rs
Labels: parser-generation, perf, ci:backport release-0.25

#4607 Fix: add wasm32 support to portable/endian.h
  lib/src/portable/endian.h
Labels: ci:backport release-0.25

#4392 Update etcetera to 0.10
  Cargo.lock
  Cargo.toml
Labels: cargo

#4567 feat: Warn about unreachable variables
  crates/generate/src/parse_grammar.rs
Labels: parser-generation

#4632 fix(rust): prevent overflow in error message calculation
  crates/cli/src/tests/query_test.rs
  lib/binding_rust/lib.rs
Labels: rust, ci:backport release-0.25

#4610 fix(bindings): use parser title in lib.rs description
  crates/cli/src/templates/lib.rs
Labels: ci:backport release-0.25

#4555 test(python): improve bindings test to detect ABI incompatibilities
  crates/cli/src/init.rs
  crates/cli/src/templates/test_binding.py
Labels: ci:backport release-0.25
