Repository tree-sitter/tree-sitter, pull requests merged in 2025-04, with the labels that each got.

#4338 Add @generated to parser.c header
  cli/generate/src/render.rs
Labels: ci:backport release-0.25

#4323 fix(rust): clarify error message for non-token reserved words
  cli/generate/src/prepare_grammar/extract_tokens.rs
Labels: ci:backport release-0.25

#4355 fix(lib): reset parser options after use
  lib/src/parser.c
Labels: c-library, ci:backport release-0.25

#4348 fix(bindings): report wasm store error in rust bindings `set_language`
  lib/binding_rust/lib.rs
Labels: wasm

#4363 fix(web): correct childWithDescendant() functionality
  lib/binding_web/lib/tree-sitter.c
  lib/binding_web/src/marshal.ts
  lib/binding_web/src/node.ts
  lib/binding_web/test/node.test.ts
Labels: wasm, ci:backport release-0.25

#4371 fix(ci): increase timeouts for flaky tests
  lib/binding_web/test/parser.test.ts
  lib/binding_web/test/query.test.ts
Labels: ci:backport release-0.25

#4372 perf(highlight): use `BTreeMap` over `IndexMap` for highlight configs
  cli/src/highlight.rs
Labels: ci:backport release-0.25

#4411 fix(generate): mark url as a Windows-only dependency
  cli/generate/Cargo.toml
Labels: cargo, ci:backport release-0.25

#4414 fix(lib): do not access the alias sequence for the `end` subtree in `ts_subtree_summarize_children`
  lib/src/subtree.c
Labels: c-library, ci:backport release-0.25
