Repository tree-sitter/tree-sitter, pull requests merged in 2025-05, with the labels that each got.

#4422 fix(query): correct `last_child_step_index` in cases where a new step wasn't created.
  cli/src/tests/query_test.rs
  lib/src/query.c
Labels: c-library, query, ci:backport release-0.25

#4440 fix(lib): return early for empty predicate step slice
  lib/src/query.c
Labels: c-library, ci:backport release-0.25

#4450 illumos has endian.h
  lib/src/portable/endian.h
Labels: c-library, ci:backport release-0.25

#4475 Revert "feat: add build sha to parser.c header comment"
  cli/build.rs
  cli/generate/build.rs
  cli/generate/src/render.rs
Labels: ci:backport release-0.25

#4319 Fix pkgconfig and use of GNUInstallDirs
  cli/src/templates/cmakelists.cmake
  lib/CMakeLists.txt
Labels: ci:backport release-0.25, build
