Repository tree-sitter/tree-sitter, pull requests merged in 2025-08, with the labels that each got.

#4650 Reserved word dsl declarations
  crates/cli/npm/dsl.d.ts
  crates/generate/src/dsl.js
  docs/src/assets/schemas/grammar.schema.json
Labels: parser-generation, ci:backport release-0.25

#4643 fix(cli): improve error message in cases where a langauge can't be found for one of many paths
  crates/cli/src/main.rs
Labels: cli, ci:backport release-0.25

#4619 fix(bindings): correct indices for `Node::utf16_text`
  crates/cli/src/tests/text_provider_test.rs
  lib/binding_rust/lib.rs
Labels: ci:backport release-0.25

#4665 fix(docs): indicate CJS env var export is different on Windows platforms
  lib/binding_web/CONTRIBUTING.md
Labels: documentation, platform:windows

#4637 Fix zig template files
  crates/cli/src/init.rs
  crates/cli/src/templates/build.zig
  crates/cli/src/templates/build.zig.zon
  crates/cli/src/templates/root.zig
  crates/cli/src/templates/test.zig
Labels: ci:backport release-0.25

#4630 fix(bindings): fix clean makefile target
  crates/cli/src/templates/makefile
Labels: ci:backport release-0.25

#4720 portable/endian: Add Haiku support
  lib/src/portable/endian.h
Labels: ci:backport release-0.25

#4532 fix(rust): EqCapture accepted cases where number of captured nodes differed by one
  crates/cli/src/tests/query_test.rs
  lib/binding_rust/lib.rs
Labels: rust, ci:backport release-0.25

#4728 fix(bindings): add tree-sitter as npm dev dependency
  crates/cli/src/init.rs
  crates/cli/src/templates/package.json
Labels: ci:backport release-0.25

#4744 fix(lib): check if an `ERROR` node is named before assuming it's the builtin error node
  crates/cli/src/tests/query_test.rs
  lib/src/language.c
  test/fixtures/test_grammars/anonymous_error/corpus.txt
  test/fixtures/test_grammars/anonymous_error/grammar.js
Labels: ci:backport release-0.25

#4747 fix(lib): allow error nodes to match when they are child nodes
  crates/cli/src/tests/query_test.rs
  lib/src/query.c
Labels: query, ci:backport release-0.25

#4153 feat(ci): build libraries on windows x64 with mingw
  .github/workflows/build.yml
Labels: github-actions, build

#4742 fix(bindings): properly detect MSVC compiler
  crates/cli/src/init.rs
  crates/cli/src/templates/setup.py
Labels: ci:backport release-0.25

#4768 fix(cli): fix DSL type declarations
  crates/cli/npm/dsl.d.ts
Labels: ci:backport release-0.25

#4207 fix typescript typechecking errors
  lib/binding_web/lib/web-tree-sitter.d.ts
  lib/binding_web/package-lock.json
  lib/binding_web/package.json
  lib/binding_web/src/index.ts
  lib/binding_web/src/language.ts
  lib/binding_web/src/marshal.ts
  lib/binding_web/src/node.ts
  lib/binding_web/src/tree_cursor.ts
  lib/binding_web/tsconfig.json
Labels: ci:backport release-0.25

#4769 feat(test): pin fixture grammars to specific commits
  crates/xtask/src/fetch.rs
  crates/xtask/src/main.rs
  test/fixtures/fixtures.json
Labels: test
